language: php

php: 
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  
env:
  - LARAVEL_VERSION="5.4.*"
  - LARAVEL_VERSION="5.5.*"
 
matrix:
    allow_failures:
        - php: hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - travis_retry composer require illuminate/support:${LARAVEL_VERSION} --no-update
  - travis_retry composer require illuminate/database:${LARAVEL_VERSION} --no-update
  - travis_retry composer install --prefer-source --no-interaction

install: composer install

script: phpunit
    - vendor/bin/phpunit
    - vendor/bin/phpstan analyse src tests --level=4
